language: generic                               
sudo: required
services:
  - docker
before_install:
  - docker build -t trubot/docker-react -f Dockerfile.dev .
script:                                                                                                                                                                                                   
  - docker run -e CI=true trubot/docker-react npm run test                                                                                                                                              
#deploy:
#  provider: elasticbeanstalk
#  region: "es"
#  app: "docker-react"
#  env: "Docker-env"
#  bucket_name: elasticbeanstalk-es-23721287987  # scalable storage in the cloud 
#  bucket_path: "docker-react"
#  on:
#    branch: master
#
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY
#
