language: generic                               
sudo: required
services:
  - docker
before_install:
  - docker build -t trubot/docker-react -f Dockerfile.dev .
script:                                                                                                                                                                                                   
  - docker run -e CI=true trubot/docker-react npm run test                                                                                                                                              
                                                                                                                                                                                                          

